# Generated by Django 5.1.1 on 2024-10-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projectdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='display_details',
            field=models.BooleanField(default=False),
        ),
    ]
