# Generated by Django 5.1.1 on 2024-10-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectdetail_display_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='display_details',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
    ]
