# Generated by Django 5.1.1 on 2024-10-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_projectdetail_display_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='display_details',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.DeleteModel(
            name='ProjectDetail',
        ),
    ]
