# Generated by Django 5.1.1 on 2024-10-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_project_image_alter_projectcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
