# Generated by Django 5.1.1 on 2024-10-11 12:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_projectcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('default_color', colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None)),
                ('heading_color', colorfield.fields.ColorField(default='#37373f', image_field=None, max_length=25, samples=None)),
                ('accent_color', colorfield.fields.ColorField(default='#ce1212', image_field=None, max_length=25, samples=None)),
                ('surface_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('contrast_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('nav_color', colorfield.fields.ColorField(default='#7f7f90', image_field=None, max_length=25, samples=None)),
                ('nav_hover_color', colorfield.fields.ColorField(default='#ce1212', image_field=None, max_length=25, samples=None)),
                ('nav_mobile_background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('nav_dropdown_background_color', colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None)),
                ('nav_dropdown_color', colorfield.fields.ColorField(default='#7f7f90', image_field=None, max_length=25, samples=None)),
                ('nav_dropdown_hover_color', colorfield.fields.ColorField(default='#ce1212', image_field=None, max_length=25, samples=None)),
            ],
        ),
    ]
