# Generated by Django 5.1.1 on 2024-10-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_themesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='What we have achieved so far', max_length=255)),
                ('description', models.TextField(default='Crafting innovative spaces with precision and creativity, building structures that stand the test of time.')),
                ('clients', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
                ('hours_of_support', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
            ],
        ),
    ]
