# Generated by Django 5.1.1 on 2024-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(blank=True, default='NAJM UL WAHAB', max_length=255, null=True),
        ),
    ]
