# Generated by Django 5.1.1 on 2024-10-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_aboutme_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('background_image_1', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('background_image_2', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('background_image_3', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
        ),
    ]
